### ISSUE TITLE
Only works on host PC

### ISSUE THREAD

**Issue by eded333** [BoredLama/stremio-jackett-addon#1]
I'm loving the addon for the exeption of not making it work over lan, or wan, only on the host pc.
Would it be possible making it a https server with a self signed certificate? As Stremio only allows add-ons that don't use SSL only from 127.0.0.1.

**Comment by BoredLama** [comment]
Yes, you are correct. It is possible to run the server with SSL and a self-signed certificate, I just hope Stremio works with URLs that have self signed certificates, as browsers (for example) don't.
 
I'll try to implement it, test it and keep you updated on this issue.

Thanks for reporting this.

**Comment by eded333** [comment]
Great! Thanks a lot!

**Comment by BoredLama** [comment]
Download the latest release:
https://github.com/BoredLama/stremio-jackett-addon/releases/tag/v1.0.2

Run the add-on with `--remote` (or alternatively set `remote` to `true` in `config.json` after you run the add-on at least once), this will also show you a URL that includes `localtunnel.me` which uses SSL.

You can use that URL to add the jackett add-on to Stremio through LAN or the Internet.
