### ISSUE TITLE
Localtunnel Custom Subdomain

### ISSUE THREAD

**Issue by eded333** [BoredLama/stremio-jackett-addon#2]
Thanks a lot for resolving the issue of remote connection so fast. 
It would be really helpfull if you could add a custom subdomain variable in the config for localtunnel, so that it would stick (If available) on every reboot, as of now it changes each time the app restarts.

**Comment by BoredLama** [comment]
yes, that's also possible

i'll keep you updated on it

**Comment by BoredLama** [comment]
Download the latest release:
https://github.com/BoredLama/stremio-jackett-addon/releases/tag/v1.0.3

Make sure to remove the old `config.json` if you'll be using the same folder as before, then run the add-on once so it creates the new config file, you can change the `subdomain` option to anything and it will be used if it is available (subdomain example: `"stremiojackett"`)
