### ISSUE TITLE
[Feature Request] Self Update

### ISSUE THREAD

**Issue by zero77** [BoredLama/stremio-jackett-addon#5]
Can you please add support for self update that users can enable in the config.
If enabled, using a separate process, it will automatically check for and install the latest version if one is found.
Thanks

**Comment by BoredLama** [comment]
This would be nice, but auto-updaters are not an easy thing to get working correctly across platforms

**Comment by zero77** [comment]
@BoredLama 
It could be updated very easley using this script in linux.
But, i dont no how you would implement this in javascript and for all OS.

```
Update() {
	cd FILE PATH OF stremio-jackett-addon
	curl -L -O $( curl -s https://api.github.com/repos/BoredLama/stremio-jackett-addon/releases | grep stremio-jackett-linux-x64.zip | grep browser_download_url | head -1 | cut -d \" -f 4 )
	rm stremio-jackett-linux-x64
	unzip stremio-jackett-linux-x64.zip
	rm stremio-jackett-linux-x64.zip
}

lversion() {
	cd FILE PATH OF stremio-jackett-addon
	./stremio-jackett-linux-x64 -v
}

rmersion() {
	curl -s https://api.github.com/repos/BoredLama/stremio-jackett-addon/releases | grep "tag_name" | head -1 | cut -d \" -f 4
}

echo local
lversion

echo remote
rmersion

if (( rmersion > lversion )); then 
	echo Updating && Update
else
	echo No Update Needed
fi
```

**Comment by BoredLama** [comment]
yeah, but we need a cross-platform solution for this.. and one that's easy to implement, reliable, and doesn't require a digital signature

**Comment by rleroi** [comment]
Why can't you convert his bash script to JS? Use os.platform() to determine which binary to download.

**Comment by BoredLama** [comment]
because Windows won't allow you to remove the binary file of a running process

**Comment by BoredLama** [comment]
I have a different plan for this anyway, I'm thinking of making a package manager for local add-ons with a web ui.

All local add-ons will be available to install in the package manager, it will take care of auto-updating add-ons, using localtunnel to make them remotely available, support auto-run on startup, etc.

The package manager just won't auto-update itself (for now, at least), but will send an OS level notification to announce when there are new releases for it.

**Comment by BoredLama** [comment]
This add-on is now part of PimpMyStremio, a local add-on manager:
https://www.reddit.com/r/StremioAddons/comments/bsgvjt/news_pimpmystremio_release_a_local_addon_manager/

PimpMyStremio auto-updates all it's installed add-ons (including Jackett), it also has a nice UI and you can configure Jackett from it's UI (instead of changing a json file)

So I consider the matter closed, the repo for the PimpMyStremio Jackett add-on is:
https://github.com/BoredLama/stremio-jackett-local
