### ISSUE TITLE
Torrent links instead of magnet links

### ISSUE THREAD

**Issue by pFNrnPE5g** [BoredLama/stremio-jackett-addon#6]
Is it possible to use .torrent links instead of magnet links, because there are private trackers that doesn't support magnet links in jackett?

**Comment by BoredLama** [comment]
uhm, i think this add-on should return torrent links too, it might be that Stremio doesn't support torrent files..
I'll look into it

**Comment by pFNrnPE5g** [comment]
I tried to open .torrent files from the tracker I use with stremio directly and it doesn't open, but it works flawlessly with an open tracker. Weird.

**Comment by BoredLama** [comment]
it's not weird, some private sites only whitelist a handful of torrent clients and even from them some specific versions.. others only blacklist torrent clients.. this is all related to what the torrent client announces as their peer ID

or maybe Stremio just doesn't support torrent files, that's ok though, preferable even, as we can convert torrent files to magnet links

**Comment by pFNrnPE5g** [comment]
I set a higher cache and "fast" bittorrent profile and it started streaming.

**Comment by BoredLama** [comment]
with or without the jackett add-on?

**Comment by pFNrnPE5g** [comment]
With jackett add-on. Works perfectly

**Comment by BoredLama** [comment]
Yeah, i checked the code of the add-on too, it seems i made it convert all torrent files to magnet links from the beginning, so this can't be an issue with the add-on.
